// Generated by Style Dictionary — do not edit manually
import { definePreset } from '@primeng/themes';
import Aura from '@primeng/themes/aura';

export default definePreset(Aura, {
  primitive: {
    indigo: {
      '400': '#6366F1',
      '500': '#4338CA',
      '600': '#3730A3',
    },
    red: {
      '500': '#DC2626',
    },
    green: {
      '500': '#16A34A',
    },
    amber: {
      '500': '#D97706',
    },
    stone: {
      '50': '#FAFAF9',
      '100': '#F5F5F4',
      '200': '#E7E5E4',
    },
    borderRadius: {
      md: '6px',
      lg: '12px',
      xl: '9999px',
    },
  },
  semantic: {
    colorScheme: {
      light: {
        primary: {
          color: '#4338CA',
          hoverColor: '#6366F1',
          activeColor: '#3730A3',
        },
        surface: {
          '0': '#FFFFFF',
          '50': '#FAFAF9',
          '100': '#F5F5F4',
          '200': '#E7E5E4',
        },
        text: {
          color: '#1C1917',
          mutedColor: '#78716C',
        },
      },
      dark: {
        primary: {
          color: '#818CF8',
          hoverColor: '#A5B4FC',
          activeColor: '#6366F1',
        },
        surface: {
          '0': '#1C1917',
          '50': '#292524',
          '100': '#44403C',
          '200': '#57534E',
        },
        text: {
          color: '#FAFAF9',
          mutedColor: '#A8A29E',
        },
      },
    },
  },
  extend: {
    spacing: {
      xs: '4px',
      sm: '8px',
      md: '16px',
      lg: '24px',
    },
  },
});
